logfile = None
LOGLEVEL = 'WARNING' #'WARNING' #ERROR, DEBUG, INFO

#Client Parameters
DOMINO_CLIENT_PORT = 9091
INTERACTIVE = 'FALSE'

CLIENT_SEQNO = 0

DOMINO_SERVER_IP = 'localhost'
DOMINO_CLI_PORT = 9100

UDID_DESIRED = '12345678123456781234567812345678'
LIST_SUPPORTED_TEMPLATES = ['tosca-nfv-v1.0']
DEFAULT_TOSCA_PUBFILE = './tosca-templates/tosca_helloworld_nfv.yaml'
TOSCA_RX_DIR = './toscafiles/'

#Server Parameters
DOMINO_SERVER_PORT = 9090
SERVER_UDID = 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'
TOSCADIR = './toscafiles/'
TOSCA_DEFAULT_FNAME = 'template1.yaml'
SERVER_DBFILE = 'dominoserver.db'
SERVER_SEQNO = 0
